# -*- coding: utf-8 -*-
"""nlp_legal_case.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0FQBso0rKBe1RX7eZ6Je5eEuZ4WVHke
"""

import numpy as np
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv("/content/drive/MyDrive/Indian_law_NLP/case_files_total.csv", engine='python')

data.info()

data.head(5)

(data.isnull().sum()/len(data))*100

data['case_category'].fillna(data['case_category'].mode(),inplace=True)

data = data.drop(columns=['name','case_type','tokens','sentences','label','proof_sentence'])

data = data.drop(columns=['Unnamed: 0'])

data = data.drop(columns=['case_info'])

data.columns

data.head()

data['judgement'].fillna(data['judgement'].mode()[0],inplace=True)

#clean text
def clean_text(text):
  text = text.lower()
  text = re.sub(r'[^a-zA-Z]',' ',text)
  text = re.sub(r'\s+',' ',text)
  text = text.strip()

  nltk.download('stopwords')
  nltk.download('wordnet')

  stop_words = set(stopwords.words('english'))
  lemmatizer = WordNetLemmatizer()

  words = text.split()

  new_words = []

  for w in words:
    if w not in stop_words:
      new_words.append(w)

  words = new_words

  new_words = []

  for w in words:
    new_words.append(lemmatizer.lemmatize(w))
  words = new_words
  return " ".join(words)

data['clean_category'] = data['case_category'].apply(clean_text)

data['clean_judgement'] = data['judgement'].apply(clean_text)

data.head()

data = data.drop(columns=['case_category','judgement'])

X = data['clean_judgement']
y = data['clean_category']

tfidf = TfidfVectorizer(max_features=5000,ngram_range=(1,2))
X = tfidf.fit_transform(data['clean_judgement'])

le = LabelEncoder()
y = le.fit_transform(data['clean_category'])

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

model = LogisticRegression(class_weight='balanced')

model.fit(X_train,y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
print("Accuracy: ",accuracy)
print("classification report : ",classification_report(y_test,y_pred))
print("confusion matrix : ", confusion_matrix(y_test,y_pred))

model_2 = RandomForestClassifier()
model_2.fit(X_train,y_train)
y_pred_2 = model_2.predict(X_test)

accuracy_2 = accuracy_score(y_test,y_pred_2)
print("Accuracy: ",accuracy_2)

model_3 = DecisionTreeClassifier()
model_3.fit(X_train,y_train)
y_pred_3 = model_3.predict(X_test)

accuracy_3 = accuracy_score(y_test,y_pred_3)
print("Accuracy: ",accuracy_3)

sample_text = "A man killed with a knife"
cleaned = clean_text(sample_text)
sample_transformed  = tfidf.transform([cleaned])
prediction = model.predict(sample_transformed)
print(le.inverse_transform(prediction))

data['clean_category'].value_counts()